# Generated by Django 4.0.1 on 2022-01-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyser_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(max_length=50)),
                ('lot_number', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('assay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsee.assays')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('test_date', models.DateTimeField()),
                ('operator', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=200)),
                ('analyser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsee.analysers')),
                ('control_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsee.controls')),
            ],
        ),
    ]
